version: "2"
services:
  plone:
    image: plone:5
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.behavior.description
    environment:
      ADDONS: "eea.behavior.description[test]"
      DEVELOP: "src/eea.behavior.description"
